name: Release Tropic

on: workflow_dispatch

jobs:

  # TODO: get version and create git tag
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Get Version
      id: version
      run: |
        version=$(awk -F "\"" '/"version":/ {print $4}' package.json)
        echo "$version"
        matches=$(git tag | grep $version | wc -l)
        if [ "$matches" != "0" ]
        then
          echo "Update the version in package.json to release new version"
          exit 1
        fi

        echo "::set-output name=version::$version"
        echo "after output setting"


  build-win:
    name: Build Windows Installer
    runs-on: windows-latest
    needs: setup

    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - run: npm install

    - name: Package Application
      run: npm run build-win

    - name: Create Installer
      run: npm run build-win-installer

    - run: ls installers/windows

  build-mac:
      name: Build Mac Installer
      runs-on: macos-latest
      needs: setup

      steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: npm install
        run: |
          npm install
          npm i electron-installer-dmg -g

      - name: Package Application
        run: npm run build-mac

      - name: Create Mac Installer
        run: npm run build-mac-installer

      - name: Upload Mac Installer
        uses: actions/upload-artifact@v2
        with:
          name: tropic_dmg
          path: installers/tropic.dmg
          retention-days: 2

  build-linux:
    name: Build Linux Installers
    runs-on: ubuntu-latest
    needs: setup

    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: npm install
      run: |
        npm install
        npm install electron-installer-debian --save-dev

    - name: Package Application
      run: npm run build-linux

    - name: Create Debian Installer
      run: npm run build-deb-installer

    - name: Create Linux Binary Tarball
      run: tar -czf installers/tropic_${{ needs.setup.outputs.version }}_x64.tar.gz builds/tropic-linux-x64/

    - name: Upload Debian Installer
      uses: actions/upload-artifact@v2
      with:
        name: tropic_debain
        path: installers/tropic_${{ needs.setup.outputs.version }}_amd64.deb
        retention-days: 2

    - name: Upload Linux Binary Tarball
      uses: actions/upload-artifact@v2
      with:
        name: tropic_tarball
        path: installers/tropic_${{ needs.setup.outputs.version }}_x64.tar.gz
        retention-days: 2

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-linux, build-mac, build-win, setup]

    steps:

    # - name: Checkout Code
    #   uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
    - run: find ./
    #   with:
    #     name: tropic_${{ needs.setup.outputs.version }}_x64.tar.gz

    # - uses: actions/download-artifact@v2
    #   with:
    #     name: tropic_${{ needs.setup.outputs.version }}_amd64.deb
    
    # - uses: actions/download-artifact@v2
    #   with:
    #     name: tropic_${{ needs.setup.outputs.version }}.dmg