name: Release Tropic

on: workflow_dispatch

jobs:

  # TODO: get version and create git tag
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.version }}

    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Get Version
      id: version
      run: |
        version=$(awk -F "\"" '/"version":/ {print $4}' package.json)
        echo "$version"
        matches=$(git tag | grep $version | wc -l)
        if [ "$matches" != "0" ]
        then
          echo "Update the version in package.json to release new version"
          exit 1
        fi

        echo "::set-output name=version::$version"
        echo "after output setting"


  build-win:
    name: Build Windows Installer
    runs-on: windows-latest
    needs: setup

    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - run: npm install

    - name: Package Application
      run: npm run build-win

    - name: Create Installer
      run: npm run build-win-installer

  build-mac:
      name: Build Mac Installer
      runs-on: macos-latest
      needs: setup

      steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: npm install
        run: |
          npm install
          npm i electron-installer-dmg -g

      - name: Package Application
        run: npm run build-mac

      - name: Create Installer
        run: npm run build-mac-installer

  build-linux:
    name: Build Linux Installers
    runs-on: ubuntu-latest
    needs: setup

    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: npm install
      run: |
        npm install
        npm install electron-installer-debian --save-dev

    - name: Package Application
      run: npm run build-linux

    - name: Create Debian Installer
      run: npm run build-deb-installer

    - name: Create Linux binary tarball
      run: npm run build-linux-bin-tar

    - run: echo "${{ needs.setup.outputs.version }}"
